<!-- Added by NI Cookie Banner Plugin created by Peter Featherstone -->

<?php if ( !isset( $_COOKIE['cookie_banner'] ) ) : ?>

    <div id="ni-cookie-banner">

        <div class='cookieBannerContainer'>

            <div class='cookieBannerText'><?php echo $data['NI_CB_BanTxt']; ?></div>

            <div class='cookieBannerRemoveContainer'>

                <div class='cookieBannerRemove'><?php echo $data['NI_CB_BtnTxt']; ?></div>

            </div>

        </div>

    </div>

 <?php endif;